/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ['./src/**/*.{js,jsx,ts,tsx}', './node_modules/react-native-sj-prime-base/dist/**/*.js'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter'],
        pretendard100: ['Pretendard-Thin'],
        pretendard200: ['Pretendard-ExtraLight'],
        pretendard300: ['Pretendard-Light'],
        pretendard400: ['Pretendard-Regular'],
        pretendard500: ['Pretendard-Medium'],
        pretendard600: ['Pretendard-SemiBold'],
        pretendard700: ['Pretendard-Bold'],
        pretendard800: ['Pretendard-ExtraBold'],
        pretendard900: ['Pretendard-Black'],
      },
      fontSize: {
        'prime-text-10': ['0.625rem', { lineHeight: '0.75rem' }],
        'prime-text-11': ['0.688rem', { lineHeight: '0.875rem' }],
        'prime-text-12': ['0.75rem', { lineHeight: '1rem' }],
        'prime-text-13': ['0.813rem', { lineHeight: '1.125rem' }],
        'prime-text-14': ['0.875rem', { lineHeight: '1.25rem' }],
        'prime-text-15': ['0.938rem', { lineHeight: '1.375rem' }],
        'prime-text-16': ['1rem', { lineHeight: '1.5rem' }],
        'prime-text-18': ['1.125rem', { lineHeight: '1.625rem' }],
        'prime-text-20': ['1.25rem', { lineHeight: '1.75rem' }],
        'prime-text-22': ['1.375rem', { lineHeight: '1.875rem' }],
        'prime-text-24': ['1.5rem', { lineHeight: '2rem' }],
        'prime-text-26': ['1.625rem', { lineHeight: '2.25rem' }],
        'prime-text-28': ['1.75rem', { lineHeight: '2.375rem' }],
        'prime-text-32': ['2rem', { lineHeight: '2.75rem' }],
        'prime-text-36': ['2.25rem', { lineHeight: '3rem' }],
        'prime-text-40': ['2.5rem', { lineHeight: '3.25rem' }],
        'prime-text-44': ['2.75rem', { lineHeight: '3.5rem' }],
        'prime-text-48': ['3rem', { lineHeight: '3.875rem' }],
        'prime-text-52': ['3.25rem', { lineHeight: '4.25rem' }],
        'prime-text-56': ['3.5rem', { lineHeight: '4.5rem' }],
        'prime-text-60': ['3.75rem', { lineHeight: '4.75rem' }],
        'prime-paragraph-13': ['0.813rem', { lineHeight: '1.25rem' }],
        'prime-paragraph-14': ['0.875rem', { lineHeight: '1.375rem' }],
        'prime-paragraph-15': ['0.938rem', { lineHeight: '1.5rem' }],
        'prime-paragraph-16': ['1rem', { lineHeight: '1.625rem' }],
        'prime-paragraph-18': ['1.125rem', { lineHeight: '1.75rem' }],
        'prime-paragraph-20': ['1.25rem', { lineHeight: '1.875rem' }],
      },
    },
  },
  plugins: [],
};
